config/routes.rb
Rails.application.routes.draw do

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/proxy', to: 'proxy#fetch'
  devise_for :users
  resources :gifs
  root to: 'gifs#index'
  get 'global_rankings', to: 'gifs#global_rankings'
  get 'random_next', to: 'gifs#randomNext'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :gifs, only: [:index, :show, :update]
  resources :rankings, only: [:index]
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gif.rb
class Gif < ApplicationRecord
    validates :link, presence: true, uniqueness: true
    has_many :rankings, dependent: :destroy

    def recalculate_global_rank
        total_ratings = rankings_array.each_with_index.sum { |count, index| count * (index * 0.5) }
        total_count = rankings_array.sum
        self.global_rank = total_count.zero? ? 0 : (total_ratings / total_count).round(2)
        save
    end

    def add_rating(rating)
        index = (rating * 2).to_i
        rankings_array[index] += 1
        recalculate_global_rank
        self.rank_count+=1;
    end

    def remove_rating(rating)
        index = (rating * 2).to_i
        rankings_array[index] -= 1
        recalculate_global_rank
        self.rank_count-=1;
    end

    def switch_rating(old_rating, new_rating)
        index = (old_rating * 2).to_i
        rankings_array[index] -= 1
        index = (new_rating * 2).to_i
        rankings_array[index] += 1
        recalculate_global_rank
    end
end

app/models/ranking.rb
class Ranking < ApplicationRecord
    belongs_to :user
    belongs_to :gif
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :rankings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @gifs = Gif.all
  end

  def show
    @user = current_user
    @gif = Gif.find(params[:id])
    @num = params[:id].to_i
    begin
      @rank = Ranking.find_by(user: @user, gif: @gif)
    rescue ActiveRecord::RecordNotFound
      @rank = nil
    end
    
  end

  def update
    @gif = Gif.find(params[:id])
    begin
      prev = Ranking.find_by(user: current_user, gif: @gif)
    rescue ActiveRecord::RecordNotFound
      prev = nil
    end

    if prev.nil?
      
      rating = params[:rating].to_f
      Ranking.create(user: current_user, gif: @gif, rank: rating)
      @gif.add_rating(rating)
    else
      rating = params[:rating].to_f
      Ranking.update(prev.id, rank: rating)
      @gif.switch_rating(prev.rank, rating)
    end
    render json: { message: 'Rating updated successfully', gif: @gif }, status: :ok
  end

  def global_rankings
    @gifs = Gif.order(global_rank: :desc)
  end

  def randomNext
    @user = current_user
    unrated_gifs = Gif.where.not(id: Ranking.where(user: @user).select(:gif_id))

    @gif = unrated_gifs.sample
    if @gif
      render json: { gif: @gif }, status: :ok
    else
      render json: { message: 'No unrated GIFs available' }, status: :not_found
    end
  end
end

app/controllers/proxy_controller.rb
require 'net/http'
require 'nokogiri'

class ProxyController < ApplicationController
  def fetch
    url = params[:url]
    if url.present?
      uri = URI.parse(url)
      response = Net::HTTP.get_response(uri)

      if response.is_a?(Net::HTTPSuccess)
        html = Nokogiri::HTML(response.body)
        gif_url = html.at_css('meta[property="og:image"]')&.[]('content')

        if gif_url
          gif_uri = URI.parse(gif_url)
          gif_response = Net::HTTP.get_response(gif_uri)

          if gif_response.is_a?(Net::HTTPSuccess)
            send_data gif_response.body, type: gif_response.content_type, disposition: 'inline'
          else
            render plain: "Failed to fetch GIF", status: :bad_request
          end
        else
          render plain: "GIF URL not found", status: :bad_request
        end
      else
        render plain: "Failed to fetch page", status: :bad_request
      end
    else
      render plain: "No URL provided", status: :bad_request
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user
        @rankings = Ranking.where(user: @user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/views/gifs/global_rankings.html.erb
<div style="display:flex; flex-wrap:wrap; ">
        <% @gifs.each_with_index do |gif,index| %>
        <div onclick="window.location.href='<%= gif_path(gif.id) %>'" style="display: flex; flex-direction:column; cursor: pointer; align-items:center; background-color: <%= case index
                                      when 0 then '#ffd700'
                                      when 1 then '#c0c0c0'
                                      when 2 then '#cd7f32'
                                      else '#f0f0f0'
                                    end %>;  padding: 10px; margin: 10px; border-radius: 5px;">
        <p> 
            #<%= index + 1 %> 
        </p>  
        <img src="/proxy?url=<%= CGI.escape(gif.link) %>" alt="bruh idk"  class="responsive-gif">
            <input 
                type="range"
                min="0"
                max="5"
                step="0.5"
                value="<%= gif.global_rank %>"
                class="rating"
                style="--val: <%= gif.global_rank%>"
                disabled
                >
        
        </div>
        <% end %>

</div>

app/views/gifs/index.html.erb
<div style="display:flex; flex-direction:column; align-items:center;">
    <script>
        function first(event)
        {
            event.preventDefault();
            fetch('/random_next')
            .then(response => {
                if (response.ok) {
                return response.json();
                } else {
                throw new Error('No unrated GIFs available');
                }
            })
            .then(data => {
                console.log('Random GIF:', data.gif);
                window.location.href = `/gifs/${data.gif.id}`;
            })
            .catch(error => {
                console.error(error.message);
                alert(error.message);
            });
        }
    </script>
    <h1 style="font-size:3rem">RANK MY GIFS</h1>
    <button id="start" onclick="first(event)" style="font-size:2rem; border-radius:5px">Start</button>
</div>

app/views/gifs/show.html.erb
<div style="display:flex; flex-direction:column; align-items:center;">
  <h1>Gif <%= @num %></h1>

  

  <img src="/proxy?url=<%= CGI.escape(@gif.link) %>" alt="bruh idk" class="responsive-gif">

  <div>
    <script>
      function sendIt(event, form) {
        event.preventDefault();

        const rating = form.querySelector('.rating').value;

        fetch('<%= gif_path(@gif.id) %>', {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': '<%= form_authenticity_token %>'
          },
          body: JSON.stringify({ rating: rating })
        })
        .then(response => response.json())
        .then(data => {
          console.log('Success:', data);
          showToast('Rating submitted successfully!');
          fetch('/random_next')
            .then(response => {
                if (response.ok) {
                return response.json();
                } else {
                throw new Error('No unrated GIFs available');
                }
            })
            .then(data => {
                console.log('Random GIF:', data.gif);
                setTimeout(() => {
                    window.location.href = `/gifs/${data.gif.id}`;
                }, 500); 
            })
            .catch(error => {
                console.error(error.message);
                alert(error.message);
            });
        })
        .catch(error => {
          console.error('Error:', error);
          showToast('Rating failed!');
        });
      }

      
    </script>
    <form onsubmit="sendIt(event,this)" style="display:flex; flex-direction:column; align-items:center;">
      <input 
        type="range"
        min="0"
        max="5"
        step="0.5"
        value="<%= @rank.nil? ? 2.5 : @rank.rank %>"
        class="rating"
        style="--val: <%= @rank.nil? ? 2.5 : @rank.rank%>;"
        oninput="this.style='--val:'+this.value"
      >
      <input type="submit" value="Submit Ranking"  style="font-size:3rem; border-radius:5px">
    </form>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ranker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
  
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
      <script>
      function showToast(message, isError = false) {
        const toast = document.createElement('div');
        toast.textContent = message;
        toast.style.position = 'fixed';
        toast.style.bottom = '20px';
        toast.style.left = '50%';
        toast.style.transform = 'translateX(-50%)';
        toast.style.backgroundColor = isError ? '#ff4d4d' : '#4caf50';
        toast.style.color = 'white';
        toast.style.padding = '10px 20px';
        toast.style.borderRadius = '5px';
        toast.style.boxShadow = '0 2px 5px rgba(0, 0, 0, 0.2)';
        toast.style.zIndex = '1000';
        document.body.appendChild(toast);

        setTimeout(() => {
          toast.style.opacity = '0';
          setTimeout(() => toast.remove(), 500);
        }, 3000);
      }
      </script>
    <nav>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          
          <% if user_signed_in? %>
            <li><a href="<%= rankings_path %>">My rankings</a></li>
          <% end %>
          <li><a href="<%= global_rankings_path %>">Global rankings</a></li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %>
          </li>
        </ul>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/rankings/index.html.erb
<div style="display:flex; flex-wrap:wrap; ">
        <% @rankings.each do |ranking| %>
        <div onclick="window.location.href='<%= gif_path(ranking.gif.id) %>'" style="display: flex; flex-direction:column; align-items:center;cursor: pointer; background-color: #f0f0f0; padding: 10px; margin: 10px; border-radius: 5px;">
            <img src="/proxy?url=<%= CGI.escape(ranking.gif.link) %>" alt="bruh idk" class="responsive-gif">
            <input 
                type="range"
                min="0"
                max="5"
                step="0.5"
                value="<%= ranking.rank %>"
                class="rating"
                style="--val: <%= ranking.rank %>"
                disabled
                >
        
        </div>
        <% end %>

</div>